### ISSUE TITLE
DynamoDB: CyclicCollection, list() method

### ISSUE THREAD

**Issue by BlueMystical** [cyclic-software/db-sdk#30]
I had managed, to successfully create a Collection, add single items and retrieve single items from it.
However, i need to  Show all the data my Collection has in it, on Github i learn it has a List() method so i tried to use it..
But the List() method do not retrieve the actual data from my objects, i mean the 'props' data.
When i try to read this 'props' given by the List() method all i get is the Last Update date.

How can i retrieve all the items in my collection, whit their data?

Not a filter, i want all the data, got no filters to apply.

**Comment by seekayel** [comment]
Sorry for the delay here. The issue is how the data is indexed. Since we are only putting the name of the collection and the primary key in the index it means that pulling data for that index will only get us those "columns" instead of the whole document for each item.

Some options we have, interested in your thoughts:
A) `scan()` method that would read every record. This could offer filters by collection (perhaps other filters as well).
B) Pull all the items via `get()` before returning the results (causes n+1 queries to be run)
C) Return an iterable object that you could cycle through to process the list.

What is the exact use case you have? Have you basically implemented B in your own code?

**Comment by BlueMystical** [comment]
I had resolved my issue and posted it on [your Discord:  HERE](https://discord.com/channels/895292239633338380/1124715344536289340/1124715344536289340)  which, by the way, did not got any kind of response from your 'Support' team.
Basically i call the Get() method for each of the 'headers' returned by the list() method, it may not be pretty or fast but i dont really have many records in the collection, so it works.
